name: Build ReactBot binaries & packages
# For now, we're only building test binaries on Linux

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-tauri:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('src-tauri/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev

      - name: Install npm dependencies
        run: npm install

      - name: Build dists
        run: npm run tauri build

      - name: Upload DEB package
        uses: actions/upload-artifact@v4
        with:
          name: reactbot-deb
          path: src-tauri/target/release/bundle/deb/*.deb

      - name: Upload RPM package
        uses: actions/upload-artifact@v4
        with:
          name: reactbot-rpm
          path: src-tauri/target/release/bundle/rpm/*.rpm

      - name: Upload AppImage package
        uses: actions/upload-artifact@v4
        with:
          name: reactbot-appimage
          path: src-tauri/target/release/bundle/appimage/*.AppImage

          
      # - name: Archive dists
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: tauri-dists
      #     path: src-tauri/target/release/bundle/